### ISSUE TITLE
Error de cache: se cargaron productos y no se actualizó el cache

### ISSUE THREAD

**Issue by PedroObed** [cesar-bedoya/TommyHilfiger#27]
Se hacen las cargas respectivas de nuevos productos en Demo o Producción pero luego de esperar que se ejecuten los jobs, no aparecen.

**Nota:** En toolkit si funciona

**Comment by carla2100** [comment]
Replicar los siguiente en Tommy:
1. Hacer un carga de nuevas: Top Categoría y sub categoría maestra.
2. Hacer un carga de nuevas: Top Categoría y sub categoría ventas.
2. Hacer carga de nuevos productos
3. Cargar la relación de categoría de venta - producto.
4. Esperar que se ejecuten los jobs UpdateIndes mode1 y DynaCacheInvalidation
5. Los producto deberían verse en la tienda, sin embargo en demo no se ven.
