### ISSUE TITLE
TOMMY demo hacerlo privado

### ISSUE THREAD

**Issue by carla2100** [cesar-bedoya/TommyHilfiger#29]
Dejar demo privado,  es posible de dejarla privada solo con contraseña, para Isidora y el diseñador

**Comment by jlrosas** [comment]
Hola Isidora

Luego de coordinar con el area de infraestructura se puede restringir el acceso a la tienda virtual tommy demo por IP Publica de origen( al igual que se restringe el acceso al management center de tommy demo) 

La ip Publica de origen la cual tendria acceso seria la oficina de Tommy Chile:

190.153.208.171  CHILE

Me confirmas que estaria OK, para solo brindar acceso a la oficina de Tommy Chile.

Saludos

**Comment by jlrosas** [comment]
Hola Isidora

Según lo coordinado en la reunión, se habilitó el acceso a Tommy demo solo para las siguientes IPs, es la misma configuración que se aplicó al management center, por lo que tienen que conectare a la red de PANAMA  o CHILE, con algún cliente, ejem teamviwer u otro designado por el administrador de la red.

IPs habilitadas:

190.153.208.171   - TOMMY CHILE
201.225.249.213   - TOMMY PANAMA
200.46.121.218     - TOMMY PANAMA

URL: 

https://tommy-demo.avatar-global.com/

Cualquier duda o consulta nos avisas.
