### ISSUE TITLE
producto que tiene la opcion de largo el largo aparece como si no tuviera stock, pero cuando uno selecciona una talla, aparece disponible

### ISSUE THREAD

**Issue by carla2100** [cesar-bedoya/TommyHilfiger#30]
Carla, te acabo de enviar un issue que encontrÃ©, lo que pasa que cuando uno entra a un producto que tiene la opcion de largo el largo aparece como si no tuviera stock, pero cuando uno selecciona una talla la talla aparece disponible
envie un print a tu correo de esto
![image](https://user-images.githubusercontent.com/30153872/48170751-c7e6e500-e2c6-11e8-9dc0-0adfc0bf0d55.png)

hay opcion que de entrada cuando el cliente abra un producto el largo se vea como disponible y que se muestre no disponible según el stock (talla que el cliente elija)

**Comment by PedroObed** [comment]
La solución es arreglando la secuencia de los Swatches por el Management Center.
