### ISSUE TITLE
Cliente no puede visualizar su pedido en Historial de Pedidos

### ISSUE THREAD

**Issue by PedroObed** [cesar-bedoya/TommyHilfiger#5]
Pedido Numero 43057104803, no aparece en el historial de pedidos del cliente.

![image 4](https://user-images.githubusercontent.com/43148715/45376390-4f60f200-b5bd-11e8-92ab-5ddc1b54735d.png)

**Comment by carla2100** [comment]
Se revisó en el XML que el pedido 43057104803 fue hecho por un usuario guest, que coiniciden con el nombre MARIA ELENA BRAVO STUARDO. Revisar en la bd de producción la fecha y hora en la que se creo  la cuenta del usuario y la fecha y hora de la orden
